[general]

# Log level
# debug=5, info=4, warning=3, error=2, fatal=1, panic=0
log_level=4


[external_api]
jwt_secret="verysecret"
bind="0.0.0.0:8085"
# bind="0.0.0.0:80"

[postgre]
# out of container
dsn="postgres://app@db/app?sslmode=disable"

# plain run
# dsn="postgres://app@localhost:5442/app?sslmode=disable"