version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    links:
      - db
    environment:
      - TEST_POSTGRES_DSN=postgres://app_test:app_test@db/app_test?sslmode=disable
    ports:
      - 8085:8085
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"

  db:
    ports:
      - 5442:5432
    image: postgres:13.2-alpine

    volumes:
      - ./.docker-compose/postgresql/initdb:/docker-entrypoint-initdb.d
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/var/lib/postgresql/data/pgdata
    # env_file:
    #   - .env
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
            
volumes:
 app-db-data:
