version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    links:
      - db
    environment:
      - TEST_POSTGRES_DSN=postgres://app_test:app_test@db/app_test?sslmode=disable
    ports:
      - 8085:80
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"

  db:
    # ports:
    #   - 5432:5432
    image: postgres:13.2-alpine

    volumes:
      - ./.docker-compose/postgresql/initdb:/docker-entrypoint-initdb.d
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/var/lib/postgresql/data/pgdata
    # env_file:
    #   - .env
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
            
volumes:
 app-db-data:
